name: antirecommender
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - annotated-types=0.7.0
  - anyio=4.8.0
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - coverage=7.6.12
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - dnspython=2.7.0
  - double-conversion=3.3.1
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fastapi=0.115.8
  - fastapi-cli=0.0.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcups=2.3.3
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libntlm=1.8
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.3
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.8.0
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.2.3
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pydantic-settings=2.8.0
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - pytest=8.3.4
  - pytest-cov=6.0.0
  - pytest-mock=3.14.0
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-multipart=0.0.20
  - python-tzdata=2025.1
  - python_abi=3.13
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - qt6-main=6.8.2
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - stack_data=0.6.3
  - starlette=0.45.3
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - uvloop=0.21.0
  - watchfiles=1.0.4
  - wayland=1.23.1
  - wcwidth=0.2.13
  - websockets=15.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
