name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Debug directory structure
      run: |
        pwd
        ls -la
        ls -la clustering-engine/

    - name: Build the Docker image
      working-directory: ./clustering-engine
      run: |
        cat environment.yml
        
        run: docker build . --file Dockerfile.run --tag antirecommender:$(date +%s)
